-- MySQL Script generated by MySQL Workbench
-- Tue May  7 09:36:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acolhimento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acolhimento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acolhimento` DEFAULT CHARACTER SET utf8 ;
USE `acolhimento` ;

-- -----------------------------------------------------
-- Table `acolhimento`.`residencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`residencia` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`residencia` (
  `codigo` INT NULL AUTO_INCREMENT,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`cartaosus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`cartaosus` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`cartaosus` (
  `codigo` INT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `cgs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`profissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`profissao` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`profissao` (
  `codigo` INT NULL AUTO_INCREMENT,
  `cbo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`escolaridade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`escolaridade` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`escolaridade` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`exame_fisico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`exame_fisico` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`exame_fisico` (
  `codigo` INT NULL AUTO_INCREMENT,
  `peso` VARCHAR(45) NOT NULL,
  `altura` VARCHAR(45) NOT NULL,
  `pressaoarterial` VARCHAR(45) NOT NULL,
  `frequenciacardiaca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`fatores_relacionados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`fatores_relacionados` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`fatores_relacionados` (
  `codigo` INT UNSIGNED NULL AUTO_INCREMENT,
  `tabagismo` VARCHAR(3) NOT NULL,
  `etilismo` VARCHAR(3) NOT NULL,
  `doencasfamiliares` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`avaliacao_enfermagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`avaliacao_enfermagem` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`avaliacao_enfermagem` (
  `codigo` INT NULL AUTO_INCREMENT,
  `exame_fisico_codigo` INT NOT NULL,
  `fatores_relacionados_codigo` INT UNSIGNED NOT NULL,
  `historiamolestiaatual` VARCHAR(300) NOT NULL,
  `historiaocupacionalpregressa` VARCHAR(300) NOT NULL,
  `anamneseocupacional` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_avaliacao_enfermagem_exame_fisico1_idx` (`exame_fisico_codigo` ASC),
  INDEX `fk_avaliacao_enfermagem_fatores_relacionados1_idx` (`fatores_relacionados_codigo` ASC),
  CONSTRAINT `fk_avaliacao_enfermagem_exame_fisico1`
    FOREIGN KEY (`exame_fisico_codigo`)
    REFERENCES `acolhimento`.`exame_fisico` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_enfermagem_fatores_relacionados1`
    FOREIGN KEY (`fatores_relacionados_codigo`)
    REFERENCES `acolhimento`.`fatores_relacionados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`relacao_trabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`relacao_trabalho` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`relacao_trabalho` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_descricao_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`situacao_trabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`situacao_trabalho` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`situacao_trabalho` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`carteira_trabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`carteira_trabalho` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`carteira_trabalho` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`informacoes_profissionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`informacoes_profissionais` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`informacoes_profissionais` (
  `codigo` INT NULL AUTO_INCREMENT,
  `quantotempoprofissaoatual` VARCHAR(45) NOT NULL,
  `profissao_codigo` INT NOT NULL,
  `relacao_trabalho_codigo` INT NOT NULL,
  `situacao_trabalho_codigo` INT NOT NULL,
  `carteira_trabalho_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_informacoes_profissionais_profissao1_idx` (`profissao_codigo` ASC),
  INDEX `fk_informacoes_profissionais_relacao_trabalho1_idx` (`relacao_trabalho_codigo` ASC),
  INDEX `fk_informacoes_profissionais_situacao_trabalho1_idx` (`situacao_trabalho_codigo` ASC),
  INDEX `fk_informacoes_profissionais_carteira_trabalho1_idx` (`carteira_trabalho_codigo` ASC),
  CONSTRAINT `fk_informacoes_profissionais_profissao1`
    FOREIGN KEY (`profissao_codigo`)
    REFERENCES `acolhimento`.`profissao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informacoes_profissionais_relacao_trabalho1`
    FOREIGN KEY (`relacao_trabalho_codigo`)
    REFERENCES `acolhimento`.`relacao_trabalho` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informacoes_profissionais_situacao_trabalho1`
    FOREIGN KEY (`situacao_trabalho_codigo`)
    REFERENCES `acolhimento`.`situacao_trabalho` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informacoes_profissionais_carteira_trabalho1`
    FOREIGN KEY (`carteira_trabalho_codigo`)
    REFERENCES `acolhimento`.`carteira_trabalho` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`beneficios_previdenciarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`beneficios_previdenciarios` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`beneficios_previdenciarios` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`status_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`status_cat` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`status_cat` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`objetivo_consulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`objetivo_consulta` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`objetivo_consulta` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`agravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`agravo` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`agravo` (
  `codigo` INT NULL AUTO_INCREMENT,
  `desdequandoaposentado` VARCHAR(100) NOT NULL,
  `realizoufisioanteriormente` VARCHAR(45) NOT NULL,
  `beneficios_previdenciarios_codigo` INT NOT NULL,
  `status_cat_codigo` INT NOT NULL,
  `objetivo_consulta_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_agravo_beneficios_previdenciarios1_idx` (`beneficios_previdenciarios_codigo` ASC),
  INDEX `fk_agravo_status_cat1_idx` (`status_cat_codigo` ASC),
  INDEX `fk_agravo_objetivo_consulta1_idx` (`objetivo_consulta_codigo` ASC),
  CONSTRAINT `fk_agravo_beneficios_previdenciarios1`
    FOREIGN KEY (`beneficios_previdenciarios_codigo`)
    REFERENCES `acolhimento`.`beneficios_previdenciarios` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agravo_status_cat1`
    FOREIGN KEY (`status_cat_codigo`)
    REFERENCES `acolhimento`.`status_cat` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agravo_objetivo_consulta1`
    FOREIGN KEY (`objetivo_consulta_codigo`)
    REFERENCES `acolhimento`.`objetivo_consulta` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`origem_encaminhamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`origem_encaminhamento` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`origem_encaminhamento` (
  `codigo` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`paciente` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`paciente` (
  `codigo` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `naturalidade` VARCHAR(150) NOT NULL,
  `nomemae` VARCHAR(150) NOT NULL,
  `datanascimento` VARCHAR(45) NOT NULL,
  `residencia_codigo` INT NOT NULL,
  `cartaosus_codigo` INT NOT NULL,
  `escolaridade_codigo` INT NOT NULL,
  `avaliacao_enfermagem_codigo` INT NOT NULL,
  `informacoes_profissionais_codigo` INT NOT NULL,
  `agravo_codigo` INT NOT NULL,
  `origem_encaminhamento_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_paciente_residencia_idx` (`residencia_codigo` ASC),
  INDEX `fk_paciente_cartaosus1_idx` (`cartaosus_codigo` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_paciente_escolaridade1_idx` (`escolaridade_codigo` ASC),
  INDEX `fk_paciente_avaliacao_enfermagem1_idx` (`avaliacao_enfermagem_codigo` ASC),
  INDEX `fk_paciente_informacoes_profissionais1_idx` (`informacoes_profissionais_codigo` ASC),
  INDEX `fk_paciente_agravo1_idx` (`agravo_codigo` ASC),
  INDEX `fk_paciente_origem_encaminhamento1_idx` (`origem_encaminhamento_codigo` ASC),
  CONSTRAINT `fk_paciente_residencia`
    FOREIGN KEY (`residencia_codigo`)
    REFERENCES `acolhimento`.`residencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_cartaosus1`
    FOREIGN KEY (`cartaosus_codigo`)
    REFERENCES `acolhimento`.`cartaosus` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_escolaridade1`
    FOREIGN KEY (`escolaridade_codigo`)
    REFERENCES `acolhimento`.`escolaridade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_avaliacao_enfermagem1`
    FOREIGN KEY (`avaliacao_enfermagem_codigo`)
    REFERENCES `acolhimento`.`avaliacao_enfermagem` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_informacoes_profissionais1`
    FOREIGN KEY (`informacoes_profissionais_codigo`)
    REFERENCES `acolhimento`.`informacoes_profissionais` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_agravo1`
    FOREIGN KEY (`agravo_codigo`)
    REFERENCES `acolhimento`.`agravo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_origem_encaminhamento1`
    FOREIGN KEY (`origem_encaminhamento_codigo`)
    REFERENCES `acolhimento`.`origem_encaminhamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
