-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 08:39:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acolhimento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acolhimento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acolhimento` DEFAULT CHARACTER SET utf8 ;
USE `acolhimento` ;

-- -----------------------------------------------------
-- Table `acolhimento`.`residencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`residencia` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`residencia` (
  `codigo` INT NULL AUTO_INCREMENT,
  `rua` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(150) NOT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`cartaosus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`cartaosus` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`cartaosus` (
  `codigo` INT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `cgs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`profissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`profissao` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`profissao` (
  `codigo` INT NULL AUTO_INCREMENT,
  `cbo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`paciente` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`paciente` (
  `codigo` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `naturalidade` VARCHAR(150) NOT NULL,
  `nomemae` VARCHAR(150) NOT NULL,
  `datanascimento` VARCHAR(45) NOT NULL,
  `residencia_codigo` INT NOT NULL,
  `cartaosus_codigo` INT NOT NULL,
  `profissao_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_paciente_residencia_idx` (`residencia_codigo` ASC),
  INDEX `fk_paciente_cartaosus1_idx` (`cartaosus_codigo` ASC),
  INDEX `fk_paciente_profissao1_idx` (`profissao_codigo` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_paciente_residencia`
    FOREIGN KEY (`residencia_codigo`)
    REFERENCES `acolhimento`.`residencia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_cartaosus1`
    FOREIGN KEY (`cartaosus_codigo`)
    REFERENCES `acolhimento`.`cartaosus` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_profissao1`
    FOREIGN KEY (`profissao_codigo`)
    REFERENCES `acolhimento`.`profissao` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`exame_fisico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`exame_fisico` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`exame_fisico` (
  `codigo` INT NULL AUTO_INCREMENT,
  `peso` VARCHAR(45) NOT NULL,
  `altura` VARCHAR(45) NOT NULL,
  `pressaoarterial` VARCHAR(45) NOT NULL,
  `frequenciacardiaca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`fatores_relacionados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`fatores_relacionados` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`fatores_relacionados` (
  `codigo` INT UNSIGNED NULL AUTO_INCREMENT,
  `tabagismo` VARCHAR(45) NOT NULL,
  `etilismo` VARCHAR(45) NOT NULL,
  `doencasfamiliares` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acolhimento`.`avaliacao_enfermagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acolhimento`.`avaliacao_enfermagem` ;

CREATE TABLE IF NOT EXISTS `acolhimento`.`avaliacao_enfermagem` (
  `codigo` INT NULL AUTO_INCREMENT,
  `exame_fisico_codigo` INT NOT NULL,
  `fatores_relacionados_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_avaliacao_enfermagem_exame_fisico1_idx` (`exame_fisico_codigo` ASC),
  INDEX `fk_avaliacao_enfermagem_fatores_relacionados1_idx` (`fatores_relacionados_codigo` ASC),
  CONSTRAINT `fk_avaliacao_enfermagem_exame_fisico1`
    FOREIGN KEY (`exame_fisico_codigo`)
    REFERENCES `acolhimento`.`exame_fisico` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_enfermagem_fatores_relacionados1`
    FOREIGN KEY (`fatores_relacionados_codigo`)
    REFERENCES `acolhimento`.`fatores_relacionados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
