/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.Log;

/**
 *
 * @author MarcoAntonio
 */
public class FramePrincipal extends javax.swing.JFrame {

    Log log;

    /**
     * Creates new form Principal
     */
    public FramePrincipal() {
        initComponents();
        log = new Log();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoAcolhimentos = new javax.swing.JList<>();
        botaoPesquisarAcolhimentos = new javax.swing.JButton();
        botaoEditarAcolhimentos = new javax.swing.JButton();
        botaoExcluirAcolhimentos = new javax.swing.JButton();
        campoPesquisarAcolhimentos = new javax.swing.JTextField();
        botaoRealizarAcolhimento = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoAcolhimentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(campoAcolhimentos);

        botaoPesquisarAcolhimentos.setText("Pesquisar");

        botaoEditarAcolhimentos.setText("Editar");
        botaoEditarAcolhimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarAcolhimentosActionPerformed(evt);
            }
        });

        botaoExcluirAcolhimentos.setText("Excluir");
        botaoExcluirAcolhimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirAcolhimentosActionPerformed(evt);
            }
        });

        campoPesquisarAcolhimentos.setText("Digite o nome do paciente...");
        campoPesquisarAcolhimentos.setToolTipText("Digite o nome do paciente...");
        campoPesquisarAcolhimentos.setNextFocusableComponent(botaoPesquisarAcolhimentos);
        campoPesquisarAcolhimentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPesquisarAcolhimentosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPesquisarAcolhimentosFocusLost(evt);
            }
        });
        campoPesquisarAcolhimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPesquisarAcolhimentosMouseClicked(evt);
            }
        });
        campoPesquisarAcolhimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisarAcolhimentosActionPerformed(evt);
            }
        });

        botaoRealizarAcolhimento.setText("Realizar Acolhimento");
        botaoRealizarAcolhimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRealizarAcolhimentoActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPesquisarAcolhimentos)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPesquisarAcolhimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoEditarAcolhimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoExcluirAcolhimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoRealizarAcolhimento, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoSair)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(campoPesquisarAcolhimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoPesquisarAcolhimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarAcolhimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluirAcolhimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRealizarAcolhimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarAcolhimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarAcolhimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditarAcolhimentosActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        try {
            /**
             * Sair do sistema
             */
            System.exit(0);
        } catch (Exception erro) {
            log.EscreveNoLog(erro.getMessage());
        }
    }//GEN-LAST:event_botaoSairActionPerformed

    private void campoPesquisarAcolhimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisarAcolhimentosActionPerformed

    }//GEN-LAST:event_campoPesquisarAcolhimentosActionPerformed

    private void campoPesquisarAcolhimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesquisarAcolhimentosMouseClicked
        /**
         * Se o campo de pesquisa de acolhimentos estiver com o texto padrao, ao
         * clickar no campo, ele limpa tudo e o campo fica vazio
         */
        if (campoPesquisarAcolhimentos.getText().toString().equals("Digite o nome do paciente...")) {
            try {
                campoPesquisarAcolhimentos.setText("");
            } catch (Exception erro) {
                log.EscreveNoLog(erro.getMessage());
            }
        }


    }//GEN-LAST:event_campoPesquisarAcolhimentosMouseClicked

    private void campoPesquisarAcolhimentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarAcolhimentosFocusGained

    }//GEN-LAST:event_campoPesquisarAcolhimentosFocusGained

    private void campoPesquisarAcolhimentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarAcolhimentosFocusLost

    }//GEN-LAST:event_campoPesquisarAcolhimentosFocusLost

    private void botaoRealizarAcolhimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRealizarAcolhimentoActionPerformed
        try {
            /**
             * Abre o JFrame de acolhimento
             */
            Acolhimento dialog = new Acolhimento(this, rootPaneCheckingEnabled);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        } catch (Exception erro) {
            log.EscreveNoLog(erro.getMessage());
        }
    }//GEN-LAST:event_botaoRealizarAcolhimentoActionPerformed

    private void botaoExcluirAcolhimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirAcolhimentosActionPerformed
        try {
            
        } catch (Exception erro) {
            log.EscreveNoLog(erro.getMessage());
        }
    }//GEN-LAST:event_botaoExcluirAcolhimentosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarAcolhimentos;
    private javax.swing.JButton botaoExcluirAcolhimentos;
    private javax.swing.JButton botaoPesquisarAcolhimentos;
    private javax.swing.JButton botaoRealizarAcolhimento;
    private javax.swing.JButton botaoSair;
    private javax.swing.JList<String> campoAcolhimentos;
    private javax.swing.JTextField campoPesquisarAcolhimentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
